import time
from app.core.celery_app import celery_app
from app.schemas.playbooks import Playbook

@celery_app.task(bind=True, max_retries=3)
def execute_playbook_step(self, step_data: dict, incident_id: str):
    """
    Executes a single atomic playbook step generated by the AI Manager Agent.
    Updates PostgreSQL state with PENDING -> RUNNING -> COMPLETED/FAILED.
    """
    action_type = step_data.get("action_type")
    payload = step_data.get("payload", {})
    
    print(f"[Incident {incident_id}] RUNNING step: {action_type}")
    
    try:
        if action_type == "slack_alert":
            # Mock HTTP call to Slack
            time.sleep(1)
            print(f"[Incident {incident_id}] COMPLETED: Sent alert to {payload.get('channel')}")
            
        elif action_type == "webhook_trigger":
            # Mock webhook to external IoT controller
            time.sleep(2)
            print(f"[Incident {incident_id}] COMPLETED: Triggered webhook {payload.get('url')}")
            
        elif action_type == "wait_for_ack":
            # In a real engine, we'd use Celery's `apply_async(countdown=...)` 
            # to suspend execution without blocking the worker thread.
            print(f"[Incident {incident_id}] PENDING: Waiting for human acknowledgment.")
            time.sleep(3)
            
        else:
            raise ValueError(f"Unknown action type: {action_type}")
            
    except Exception as exc:
        print(f"[Incident {incident_id}] FAILED step: {action_type}. Retrying...")
        self.retry(exc=exc, countdown=5)

@celery_app.task
def orchestrate_incident_playbook(playbook_data: dict):
    """
    Kicks off the sequence of steps defined in the playbook.
    """
    playbook = Playbook(**playbook_data)
    
    for step in playbook.steps:
        # We chain these or execute them sequentially depending on the SOP
        execute_playbook_step.delay(step.dict(), playbook.incident_id)
